import images from "./images";

export const siteStats = [
  {
    title: "Total Users",
    value: "1,500",
    description: "+5% increase from last month",
    icon: images.user,
    bgIcon: "bg-[#620748]",
    bgCard: "bg-[#470434]",
    textColor: "white",
    statChangeColor: "text-green-500",
  },
  {
    title: "Total Riders",
    value: "120",
    description: "+5% increase from last month",
    icon: images.rider,
    bgIcon: "bg-[#08385D]",
    bgCard: "bg-[#042A47]",
    textColor: "white",
    statChangeColor: "text-green-500",
  },
  {
    title: "Activated Riders",
    value: "80",
    description: "+5% increase from last month",
    icon: images.activate,
    bgIcon: "bg-[#601A08]",
    bgCard: "bg-[#471204]",
    textColor: "white",
    statChangeColor: "text-green-500",
  },
  {
    title: "Total Revenue",
    value: "₦250,500",
    description: "-25% decrease from last month",
    icon: images.revenue,
    bgIcon: "bg-[#085E1B]",
    bgCard: "bg-[#044713]",
    textColor: "white",
    statChangeColor: "text-red-500",
  },
];

export const rideStats = [
  {
    title: "Total Deliveries",
    value: "1,500",
    description: "+5% increase from last month",
    icon: images.user,
    bgIcon: "bg-[#620748]",
    bgCard: "bg-[#470434]",
    textColor: "white",
    statChangeColor: "text-green-500",
  },
  {
    title: "Scheduled Rides",
    value: "120",
    description: "+5% increase from last month",
    icon: images.schedule,
    bgIcon: "bg-[#08385D]",
    bgCard: "bg-[#042A47]",
    textColor: "white",
    statChangeColor: "text-green-500",
  },
  {
    title: "Active Rides",
    value: "80",
    description: "+5% increase from last month",
    icon: images.activate,
    bgIcon: "bg-[#601A08]",
    bgCard: "bg-[#471204]",
    textColor: "white",
    statChangeColor: "text-green-500",
  },
  {
    title: "Completed Rides",
    value: "100",
    description: "-25% decrease from last month",
    icon: images.completed,
    bgIcon: "bg-[#085E1B]",
    bgCard: "bg-[#044713]",
    textColor: "white",
    statChangeColor: "text-red-500",
  },
];
